<?php

namespace App\Form;

use App\Entity\Batiment;
use App\Entity\SearchChambre;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChambreSearchType extends AbstractType
{
    private $type=['Individuel','A deux'];
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('numchambre', TextType::class,[
                'required'=>false,
                'attr'=>[
                'placeholder'=>'Numero Chambre'
                    ]
            ])
            ->add('type', ChoiceType::class,[
                'required'=>false,
                'placeholder'=>'type de chambre',
                'choices'=>[
                    array_combine($this->type,$this->type)
                ]
            ])
            ->add('batiment', EntityType::class,[
                'required'=>false,

                'placeholder'=>'Numero Batiment',
                'class'=> Batiment::class,
                'choice_label' =>'numBatiment',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SearchChambre::class,
            'method'=>'get',
            'csrf_protection'=>false
        ]);
    }
    public function getBlockPrefix()
    {
        return''; // TODO: Change the autogenerated stub
    }
}
