<?php

namespace App\Form;

use App\Entity\Departement;
use App\Entity\Etudiant;
use App\Entity\SearchEtudiant;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EtudiantSearchType extends AbstractType
{
    private $type=['Boursier Loge','Boursier Non Loge','Non Boursier'];
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('matricule', TextType::class,[
                'required'=>false,
                'attr'=>[
                'placeholder'=>'matricule'
                    ]
            ])
            ->add('type', ChoiceType::class,[
                'required'=>false,
                'placeholder'=>'type d\'etudiant',
                'choices'=>[
                    array_combine($this->type,$this->type)
                ]
            ])
            ->add('departement', EntityType::class,[
                'required'=>false,

                'placeholder'=>'departement',
                'class'=> Departement::class,
                'choice_label' => 'nomDepartement',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SearchEtudiant::class,
            'method'=>'get',
            'csrf_protection'=>false
        ]);
    }
    public function getBlockPrefix()
    {
        return''; // TODO: Change the autogenerated stub
    }
}
